package com.sad.entites;

// Generated Jan 21, 2016 9:59:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "test")
public class Message implements java.io.Serializable {

	private int messageId;
	private Account account;
	private Productdetail productdetail;
	private String messageNameCompare;
	private String messageDetail;
	private Date timeMessage;

	public Message() {
	}

	public Message(int messageId, Account account, Productdetail productdetail) {
		this.messageId = messageId;
		this.account = account;
		this.productdetail = productdetail;
	}

	public Message(int messageId, Account account, Productdetail productdetail,
			String messageNameCompare, String messageDetail, Date timeMessage) {
		this.messageId = messageId;
		this.account = account;
		this.productdetail = productdetail;
		this.messageNameCompare = messageNameCompare;
		this.messageDetail = messageDetail;
		this.timeMessage = timeMessage;
	}

	@Id
	@Column(name = "messageID", unique = true, nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false)
	public Productdetail getProductdetail() {
		return this.productdetail;
	}

	public void setProductdetail(Productdetail productdetail) {
		this.productdetail = productdetail;
	}

	@Column(name = "messageNameCompare", length = 1000)
	public String getMessageNameCompare() {
		return this.messageNameCompare;
	}

	public void setMessageNameCompare(String messageNameCompare) {
		this.messageNameCompare = messageNameCompare;
	}

	@Column(name = "messageDetail", length = 1000)
	public String getMessageDetail() {
		return this.messageDetail;
	}

	public void setMessageDetail(String messageDetail) {
		this.messageDetail = messageDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeMessage", length = 19)
	public Date getTimeMessage() {
		return this.timeMessage;
	}

	public void setTimeMessage(Date timeMessage) {
		this.timeMessage = timeMessage;
	}

}
