package com.sad.entites;

// Generated Jan 21, 2016 9:59:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productdetail generated by hbm2java
 */
@Entity
@Table(name = "productdetail", catalog = "test")
public class Productdetail implements java.io.Serializable {

	private int id;
	private String name;
	private String brand;
	private String screen;
	private String generation;
	private Integer hdd;
	private Integer price;
	private String imageLink;
	private String vga;
	private String ram;
	private String os;
	private Integer weight;
	private Integer pin;
	private Boolean nowater;
	private Boolean touch;
	private Integer onestart;
	private Integer twostart;
	private Integer threestart;
	private Integer fourstart;
	private Integer sumstart;
	private Set<Message> messages = new HashSet<Message>(0);

	public Productdetail() {
	}

	public Productdetail(int id) {
		this.id = id;
	}

	public Productdetail(int id, String name, String brand, String screen,
			String generation, Integer hdd, Integer price, String imageLink,
			String vga, String ram, String os, Integer weight, Integer pin,
			Boolean nowater, Boolean touch, Integer onestart, Integer twostart,
			Integer threestart, Integer fourstart, Integer sumstart,
			Set<Message> messages) {
		this.id = id;
		this.name = name;
		this.brand = brand;
		this.screen = screen;
		this.generation = generation;
		this.hdd = hdd;
		this.price = price;
		this.imageLink = imageLink;
		this.vga = vga;
		this.ram = ram;
		this.os = os;
		this.weight = weight;
		this.pin = pin;
		this.nowater = nowater;
		this.touch = touch;
		this.onestart = onestart;
		this.twostart = twostart;
		this.threestart = threestart;
		this.fourstart = fourstart;
		this.sumstart = sumstart;
		this.messages = messages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "brand", length = 45)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "screen", length = 45)
	public String getScreen() {
		return this.screen;
	}

	public void setScreen(String screen) {
		this.screen = screen;
	}

	@Column(name = "generation", length = 45)
	public String getGeneration() {
		return this.generation;
	}

	public void setGeneration(String generation) {
		this.generation = generation;
	}

	@Column(name = "hdd")
	public Integer getHdd() {
		return this.hdd;
	}

	public void setHdd(Integer hdd) {
		this.hdd = hdd;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "imageLink")
	public String getImageLink() {
		return this.imageLink;
	}

	public void setImageLink(String imageLink) {
		this.imageLink = imageLink;
	}

	@Column(name = "vga", length = 45)
	public String getVga() {
		return this.vga;
	}

	public void setVga(String vga) {
		this.vga = vga;
	}

	@Column(name = "ram", length = 45)
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	@Column(name = "os", length = 45)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "pin")
	public Integer getPin() {
		return this.pin;
	}

	public void setPin(Integer pin) {
		this.pin = pin;
	}

	@Column(name = "nowater")
	public Boolean getNowater() {
		return this.nowater;
	}

	public void setNowater(Boolean nowater) {
		this.nowater = nowater;
	}

	@Column(name = "touch")
	public Boolean getTouch() {
		return this.touch;
	}

	public void setTouch(Boolean touch) {
		this.touch = touch;
	}

	@Column(name = "onestart")
	public Integer getOnestart() {
		return this.onestart;
	}

	public void setOnestart(Integer onestart) {
		this.onestart = onestart;
	}

	@Column(name = "twostart")
	public Integer getTwostart() {
		return this.twostart;
	}

	public void setTwostart(Integer twostart) {
		this.twostart = twostart;
	}

	@Column(name = "threestart")
	public Integer getThreestart() {
		return this.threestart;
	}

	public void setThreestart(Integer threestart) {
		this.threestart = threestart;
	}

	@Column(name = "fourstart")
	public Integer getFourstart() {
		return this.fourstart;
	}

	public void setFourstart(Integer fourstart) {
		this.fourstart = fourstart;
	}

	@Column(name = "sumstart")
	public Integer getSumstart() {
		return this.sumstart;
	}

	public void setSumstart(Integer sumstart) {
		this.sumstart = sumstart;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productdetail")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
